"""initial schema

Revision ID: 19210203a29b
Revises: 
Create Date: 2026-02-13 00:09:58.378549
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19210203a29b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nearby_airports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('airport_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('metro_area', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('natural_language_input', sa.Text(), nullable=True),
    sa.Column('parsed_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('origin_airport', sa.String(length=10), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('destination_airport', sa.String(length=10), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('flexibility_days', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_leg_id', sa.UUID(), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('cheapest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('most_expensive_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_log_id', sa.UUID(), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=False),
    sa.Column('airline_name', sa.String(length=100), nullable=False),
    sa.Column('flight_numbers', sa.String(length=100), nullable=False),
    sa.Column('origin_airport', sa.String(length=10), nullable=False),
    sa.Column('destination_airport', sa.String(length=10), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('stop_airports', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.Column('seats_remaining', sa.Integer(), nullable=True),
    sa.Column('is_alternate_airport', sa.Boolean(), nullable=False),
    sa.Column('is_alternate_date', sa.Boolean(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_log_id'], ['search_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_leg_id', sa.UUID(), nullable=False),
    sa.Column('flight_option_id', sa.UUID(), nullable=False),
    sa.Column('justification_note', sa.Text(), nullable=True),
    sa.Column('slider_position', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_option_id'], ['flight_options.id'], ),
    sa.ForeignKeyConstraint(['trip_leg_id'], ['trip_legs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selections')
    op.drop_table('flight_options')
    op.drop_table('search_logs')
    op.drop_table('trip_legs')
    op.drop_table('trips')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('nearby_airports')
    # ### end Alembic commands ###
